spring:
  cloud:
    gateway:
      routes:
      - id: servicio-productos
        uri: lb://servicio-productos
        predicates:
        - Path=/productos/**
        filters:
        - StripPrefix=1
      - id: servicio-items
        uri: lb://servicio-items
        predicates:
        - Path=/items/**
        filters:
        - StripPrefix=1
      - id: servicio-autentificacion
        uri: lb://servicio-autentificacion
        predicates:
        - Path=/auth/**
        filters:
        - StripPrefix=1
      - id: servicio-emails
        uri: lb://servicio-emails
        predicates:
        - Path=/emails/**
        filters:
        - StripPrefix=1
      - id: servicio-tokens
        uri: lb://servicio-tokens
        predicates:
        - Path=/tokens/**
        filters:
        - StripPrefix=1