spring:
  cloud:
    gateway:
      routes:
      - id: servicio-productos
        uri: lb://servicio-productos
        predicates:
        - Path=/productos/**
        filters:
        - StripPrefix=1
      - id: servicio-items
        uri: lb://servicio-items
        predicates:
        - Path=/items/**
        filters:
        - StripPrefix=1